version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env.test

  node_app:
    container_name: node_app
    build: ./back-end/
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./back-end/.env.test

volumes:
  postgres:
