version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end
    command: bash -c "npm run prisma:deploy && npm run prisma:seed && npm start"
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./back-end/.env

  react_app:
    build: ./front-end
    container_name: react_app
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - react_app

volumes:
  postgres:
  build_react:
