name: Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  AWSDeploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make backend envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end/
          file_name: .env
      - name: Make frontend envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_BASE_URL: "/api"
          directory: front-end/
          file_name: .env
      - name: Run app
        run: docker-compose -f docker-compose-prod.yml up --build -d
